Add chelsio_adapter_config.py and binaries
truenas/binaries pull request #4
Opened 2024-04-29 10:48 UTC by themylogin

2024-04-29 10:48 UTC, bugclerk commented
Jira URL: https://ixsystems.atlassian.net/browse/NAS-128567

2024-04-29 12:31 UTC, yocalebo requested changes
Please add a description to the PR outlining:
1. what version of Uwire you used
2. update debian changelog to also specify the version of uwire

2024-04-30 11:17 UTC, yocalebo approved these changes

2024-04-30 11:32 UTC, merged

2024-04-30 11:32 UTC, bugclerk commented
Unable to perform the following backports: backport-24.04.1.
Available versions: 13.0, 13.3, 23.10-RC.1, 23.10.3, 24.04-BETA.1, 24.04-RC.1, 24.04.0, 24.04.1, 24.10.

2024-04-30 11:32 UTC, bugclerk commented
JIRA ticket https://ixsystems.atlassian.net/browse/NAS-128567 is targeted to the following versions which have not received their corresponding PRs: 24.04.1

2024-04-30 11:32 UTC, bugclerk commented
This PR has been merged and conversations have been locked.
If you would like to discuss more about this issue please use our forums or raise a Jira ticket.

2024-04-30 11:32 UTC, themylogin commented
backport

2024-04-30 11:33 UTC, themylogin commented
time 1:00

2024-04-30 11:33 UTC, bugclerk commented
Time tracking failed:
```Traceback (most recent call last):
  File "/home/bugclerk/bugclerk/__main__.py", line 1197, in track_time
    comment.create_reaction('+1')
  File "/home/bugclerk/venv/lib/python3.11/site-packages/github/IssueComment.py", line 160, in create_reaction
    headers, data = self._requester.requestJsonAndCheck(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bugclerk/venv/lib/python3.11/site-packages/github/Requester.py", line 315, in requestJsonAndCheck
    return self.__check(
           ^^^^^^^^^^^^^
  File "/home/bugclerk/venv/lib/python3.11/site-packages/github/Requester.py", line 340, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 403 {"message": "Must have admin rights to Repository.", "documentation_url": "https://docs.github.com/rest/reactions/reactions#create-reaction-for-an-issue-comment"}
```